/* global use, db */
// MongoDB Playground
// Use Ctrl+Space inside a snippet or a string literal to trigger completions.

// The current database to use.
use("TNEASeatMatrix");
// Search for documents in the current collection.
// Assuming you have connected to the MongoDB database and have a reference to a collection called "myCollection"

// Update a single document that matches a condition

// CCODE 1
// const myCollections = db.getCollection("users");
// const filter = { _id: ObjectId("640cc8bd8d1ef89ebf0048da") }; // specify the condition for the document to update
// const update = {
//   $set: {
//     CourseDetails: [
//       {
//         courseName: { label: "BIO MEDICAL ENGINEERING  (SS)", value: "BY" },
//         courseCode: "BY",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 60,
//         Govt: 58,
//         Surrender: 0,
//         Management: 2,
//         SWS: 58,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: { label: "CIVIL  ENGINEERING ", value: "CE" },
//         courseCode: "CE",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 60,
//         Govt: 59,
//         Surrender: 0,
//         Management: 1,
//         SWS: 59,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: {
//           label: "COMPUTER SCIENCE AND ENGINEERING (SS)",
//           value: "CM",
//         },
//         courseCode: "CM",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 120,
//         Govt: 118,
//         Surrender: 0,
//         Management: 2,
//         SWS: 118,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: { label: "COMPUTER SCIENCE AND ENGINEERING", value: "CS" },
//         courseCode: "CS",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 60,
//         Govt: 59,
//         Surrender: 0,
//         Management: 1,
//         SWS: 59,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: {
//           label: "ELECTRONICS AND COMMUNICATION ENGINEERING",
//           value: "EC",
//         },
//         courseCode: "EC",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 60,
//         Govt: 59,
//         Surrender: 0,
//         Management: 1,
//         SWS: 59,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: {
//           label: "ELECTRICAL AND ELECTRONICS ENGINEERING",
//           value: "EE",
//         },
//         courseCode: "EE",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 60,
//         Govt: 59,
//         Surrender: 0,
//         Management: 1,
//         SWS: 59,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: {
//           label: "ELECTRONICS AND COMMUNICATION ENGINEERING (SS)",
//           value: "EM",
//         },
//         courseCode: "EM",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 60,
//         Govt: 58,
//         Surrender: 0,
//         Management: 2,
//         SWS: 58,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: { label: "GEO INFORMATICS", value: "GI" },
//         courseCode: "GI",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 40,
//         Govt: 39,
//         Surrender: 0,
//         Management: 1,
//         SWS: 39,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: { label: "INDUSTRIAL ENGINEERING", value: "IE" },
//         courseCode: "IE",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 40,
//         Govt: 38,
//         Surrender: 0,
//         Management: 2,
//         SWS: 38,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: { label: "INFORMATION TECHNOLOGY (SS)", value: "IM" },
//         courseCode: "IM",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 120,
//         Govt: 118,
//         Surrender: 0,
//         Management: 2,
//         SWS: 118,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: {
//           label: "MATERIAL SCIENCE AND ENGINEERING (SS)",
//           value: "MA",
//         },
//         courseCode: "MA",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 30,
//         Govt: 29,
//         Surrender: 0,
//         Management: 1,
//         SWS: 29,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: { label: "MECHANICAL ENGINEERING", value: "ME" },
//         courseCode: "ME",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 120,
//         Govt: 118,
//         Surrender: 0,
//         Management: 2,
//         SWS: 118,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: { label: "MINING ENGINEERING", value: "MI" },
//         courseCode: "MI",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 30,
//         Govt: 29,
//         Surrender: 0,
//         Management: 1,
//         SWS: 29,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: { label: "MANUFACTURING ENGINEERING", value: "MN" },
//         courseCode: "MN",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 60,
//         Govt: 59,
//         Surrender: 0,
//         Management: 1,
//         SWS: 59,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: { label: "PRINTING AND PACKING TECHNOLOGY", value: "PT" },
//         courseCode: "PT",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 40,
//         Govt: 39,
//         Surrender: 0,
//         Management: 1,
//         SWS: 39,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: { label: "CIVIL ENGINEERING (TAMIL MEDIUM)", value: "XC" },
//         courseCode: "XC",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 30,
//         Govt: 30,
//         Surrender: 0,
//         Management: 0,
//         SWS: 30,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: {
//           label: "MECHANICAL ENGINEERING (TAMIL MEDIUM)",
//           value: "XM",
//         },
//         courseCode: "XM",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 30,
//         Govt: 30,
//         Surrender: 0,
//         Management: 0,
//         SWS: 30,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//     ],
//   },
// }; // specify the field and its new value using the $set operator

// myCollections.updateOne(filter, update);

//CCODE 2
// const myCollections = db.getCollection("users");
// const filter = { _id: ObjectId("640cc8bd8d1ef89ebf0048db") }; // specify the condition for the document to update
// const update = {
//   $set: {
//     CourseDetails: [
//       {
//         courseName: { label: "APPAREL TECHNOLOGY (SS)", value: "AP" },
//         courseCode: "AP",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 30,
//         Govt: 30,
//         Surrender: 0,
//         Management: 0,
//         SWS: 30,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },

//       {
//         courseName: { label: "CHEMICAL  ENGINEERING ", value: "CH" },
//         courseCode: "CH",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 60,
//         Govt: 58,
//         Surrender: 0,
//         Management: 2,
//         SWS: 58,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: { label: "CHEMICAL  ENGINEERING (SS)", value: "CL" },
//         courseCode: "CL",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 60,
//         Govt: 59,
//         Surrender: 0,
//         Management: 1,
//         SWS: 59,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: { label: "CERAMIC TECHNOLOGY (SS)", value: "CR" },
//         courseCode: "CR",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 60,
//         Govt: 60,
//         Surrender: 0,
//         Management: 0,
//         SWS: 60,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: { label: "FOOD TECHNOLOGY (SS)", value: "FS" },
//         courseCode: "FS",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 40,
//         Govt: 39,
//         Surrender: 0,
//         Management: 1,
//         SWS: 39,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: { label: "INDUSTRIAL BIO TECHNOLOGY", value: "IB" },
//         courseCode: "IB",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 40,
//         Govt: 30,
//         Surrender: 0,
//         Management: 10,
//         SWS: 30,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: { label: "INDUSTRIAL BIO TECHNOLOGY (SS)", value: "IS" },
//         courseCode: "IS",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 20,
//         Govt: 20,
//         Surrender: 0,
//         Management: 0,
//         SWS: 20,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: { label: "LEATHER TECHNOLOGY", value: "LE" },
//         courseCode: "LE",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 60,
//         Govt: 59,
//         Surrender: 0,
//         Management: 1,
//         SWS: 59,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: { label: "PHARMACEUTICAL TECHNOLOGY (SS)", value: "PM" },
//         courseCode: "PM",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 60,
//         Govt: 59,
//         Surrender: 0,
//         Management: 1,
//         SWS: 59,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: {
//           label: "PETROLEUM ENGINEERING AND TECHNOLOGY (SS)",
//           value: "PP",
//         },
//         courseCode: "PP",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 60,
//         Govt: 60,
//         Surrender: 0,
//         Management: 0,
//         SWS: 60,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//       {
//         courseName: { label: "TEXTILE TECHNOLOGY", value: "TX" },
//         courseCode: "TX",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },
//         intake: 60,
//         Govt: 59,
//         Surrender: 0,
//         Management: 1,
//         SWS: 59,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },

//     ],
//   },
// }; // specify the field and its new value using the $set operator

// myCollections.updateOne(filter, update);

//CCODE 3
// const myCollections = db.getCollection("users");
// const filter = { _id: ObjectId("640cc8bd8d1ef89ebf0048dc") }; // specify the condition for the document to update
// const update = {
//   $set: {
//     CourseDetails: [
//       {
//         courseName: { label: "B.Plan", value: "BP" },
//         courseCode: "BP",
//         accredation: { value: "ACC", label: "Accredited", disabled: false },

//         intake: 40,
//         Govt: 40,
//         Surrender: 0,
//         Management: 0,
//         SWS: 40,
//         Quota: 1,
//         Added: 0,
//         Pending: 0,
//         error: false,
//       },
//     ],
//   },
// }; // specify the field and its new value using the $set operator
// myCollections.updateOne(filter, update);

//CCODE 4
const myCollections = db.getCollection("users");
const filter = { _id: ObjectId("640cc8bd8d1ef89ebf0048dd") }; // specify the condition for the document to update
const update = {
  $set: {
    CourseDetails: [
      {
        courseName: { label: "AERONAUTICAL ENGINEERING", value: "AE" },
        courseCode: "AE",
        accredation: { value: "ACC", label: "Accredited", disabled: false },
        intake: 60,
        Govt: 59,
        Surrender: 0,
        Management: 1,
        SWS: 59,
        Quota: 1,
        Added: 0,
        Pending: 0,
        error: false,
      },
      {
        courseName: {
          label: "ARTIFICIAL INTELLIGENCE AND DATA SCIENCE (SS)",
          value: "AT",
        },
        courseCode: "AT",
        accredation: { value: "ACC", label: "Accredited", disabled: false },
        intake: 60,
        Govt: 60,
        Surrender: 0,
        Management: 0,
        SWS: 60,
        Quota: 1,
        Added: 0,
        Pending: 0,
        error: false,
      },
      {
        courseName: { label: "AUTOMOBILE ENGINEERING", value: "AU" },
        courseCode: "AU",
        accredation: { value: "ACC", label: "Accredited", disabled: false },
        intake: 60,
        Govt: 59,
        Surrender: 0,
        Management: 1,
        SWS: 59,
        Quota: 1,
        Added: 0,
        Pending: 0,
        error: false,
      },
      {
        courseName: {
          label: "COMPUTER SCIENCE AND ENGINEERING (SS)",
          value: "CM",
        },
        courseCode: "CM",
        accredation: { value: "ACC", label: "Accredited", disabled: false },
        intake: 60,
        Govt: 59,
        Surrender: 0,
        Management: 1,
        SWS: 59,
        Quota: 1,
        Added: 0,
        Pending: 0,
        error: false,
      },
      {
        courseName: { label: "COMPUTER SCIENCE AND ENGINEERING", value: "CS" },
        courseCode: "CS",
        accredation: { value: "ACC", label: "Accredited", disabled: false },
        intake: 60,
        Govt: 59,
        Surrender: 0,
        Management: 1,
        SWS: 59,
        Quota: 1,
        Added: 0,
        Pending: 0,
        error: false,
      },
      {
        courseName: {
          label: "ELECTRONICS AND COMMUNICATION ENGINEERING",
          value: "EC",
        },
        courseCode: "EC",
        accredation: { value: "ACC", label: "Accredited", disabled: false },
        intake: 60,
        Govt: 59,
        Surrender: 0,
        Management: 1,
        SWS: 59,
        Quota: 1,
        Added: 0,
        Pending: 0,
        error: false,
      },
      {
        courseName: {
          label: "ELECTRONICS AND INSTRUMENTATION ENGINEERING",
          value: "EI",
        },
        courseCode: "EI",
        accredation: { value: "ACC", label: "Accredited", disabled: false },
        intake: 60,
        Govt: 59,
        Surrender: 0,
        Management: 1,
        SWS: 59,
        Quota: 1,
        Added: 0,
        Pending: 0,
        error: false,
      },
      {
        courseName: {
          label: "ELECTRONICS AND COMMUNICATION ENGINEERING (SS)",
          value: "EM",
        },
        courseCode: "EM",
        accredation: { value: "ACC", label: "Accredited", disabled: false },
        intake: 60,
        Govt: 58,
        Surrender: 0,
        Management: 2,
        SWS: 58,
        Quota: 1,
        Added: 0,
        Pending: 0,
        error: false,
      },
      {
        courseName: { label: "INFORMATION TECHNOLOGY (SS)", value: "IM" },
        courseCode: "IM",
        accredation: { value: "ACC", label: "Accredited", disabled: false },
        intake: 120,
        Govt: 118,
        Surrender: 0,
        Management: 2,
        SWS: 118,
        Quota: 1,
        Added: 0,
        Pending: 0,
        error: false,
      },
      {
        courseName: { label: "PRODUCTION ENGINEERING", value: "PR" },
        courseCode: "PR",
        accredation: { value: "ACC", label: "Accredited", disabled: false },
        intake: 60,
        Govt: 59,
        Surrender: 0,
        Management: 1,
        SWS: 59,
        Quota: 1,
        Added: 0,
        Pending: 0,
        error: false,
      },
      {
        courseName: { label: "ROBOTICS AND AUTOMATION (SS)", value: "RA" },
        courseCode: "RA",
        accredation: { value: "ACC", label: "Accredited", disabled: false },
        intake: 30,
        Govt: 29,
        Surrender: 0,
        Management: 1,
        SWS: 29,
        Quota: 1,
        Added: 0,
        Pending: 0,
        error: false,
      },
      {
        courseName: { label: "RUBBER AND PLASTIC TECHNOLOGY", value: "RP" },
        courseCode: "RP",
        accredation: { value: "ACC", label: "Accredited", disabled: false },
        intake: 60,
        Govt: 60,
        Surrender: 0,
        Management: 0,
        SWS: 60,
        Quota: 1,
        Added: 0,
        Pending: 0,
        error: false,
      },
    ],
  },
}; // specify the field and its new value using the $set operator
myCollections.updateOne(filter, update);
